#Validation plots to ensure HCR is behaving as expected

#Load packages
library(r4ss)
#library(plyr)
library(dplyr)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(fitdistrplus)

#read in historical SSB and Recruits from the 1952 start 2023 SAM
rdat=read.csv("C:/Users/desiree.tommasi/Documents/Bluefin/Recruits.csv",header=TRUE)
names(rdat)[1]="Year"
ssbdat=read.csv("C:/Users/desiree.tommasi/Documents/Bluefin/SSB.csv",header=TRUE)
names(ssbdat)[1]="Year"
fdat=read.csv("C:/Users/desiree.tommasi/Documents/Bluefin/FSPR.csv",header=TRUE)
names(fdat)[1]="Year"
cdat=read.csv("C:/Users/desiree.tommasi/Documents/Bluefin/Catch.csv",header=TRUE)
names(cdat)[1]="Year"

#Read in the MSE simulation data
#These are the output generated by the read_output_pbfMSE.R function
#are saved in the MSe directory strucutre of ../PBF_MSE/hs/hcr/scn

#Specify path of parent directory
pdir = "C:/Users/desiree.tommasi/Documents/Bluefin/PBF_MSE/"

#set working directory to where all functions needed are stored
setwd(paste(pdir,"Rcode/R_funs", sep = ""))

#source all the functions
file.sources = list.files()
sapply(file.sources,source,.GlobalEnv)

#specific the harvest strategy
hsnum=1
hcrnumv = c(101:108,111,112)
scnum = 1

hs = paste(hsnum, "/", sep = "")
scn = paste(scnum, "/", sep = "")

#potential threshold, limit, and target reference points for the two control points HCRs listed above
btv=c(0.2,0.25,0.2,0.25,0.25,0.2,0.2,0.2,0.15,0.2)
blv=c(0.15,0.15,0.15,0.15,0.20,0.1,0.1,0.06,0.077,0.077)
trpv = c(0.3,0.3,0.4,0.4,0.4,0.3,0.25,0.3,0.3,0.3)
fminv= c(rep(0.1,5), 0.43,0.67,NA, 0.05,0.05)

#Extract results of first hcr
hcrnum=hcrnumv[1]
hcr = paste(hcrnum, "/", sep = "")
bt = btv[1]
bl = blv[1]
trp = trpv[1]
fmin = fminv[1]

dat1a=read.table(paste(pdir,hs,hcr, scn, "/outmat",hsnum,hcrnum,scnum,".txt", sep =""))
dat1a$hs="1a"
dat1a$hcr=hcrnum
dat1a$scn=scnum
dat1a$trp=trp
dat1a$lrp=bl
dat1a$thrp=bt
dat1a$fmin=fmin

for (j in 2:length(hcrnumv)){
  hcrnum=hcrnumv[j]
  hcr = paste(hcrnum, "/", sep = "")
  bt = btv[j]
  bl = blv[j]
  trp = trpv[j]
  fmin = fminv[j]
  
  dat=read.table(paste(pdir,hs,hcr, scn, "/outmat",hsnum,hcrnum,scnum,".txt", sep =""))
  dat$hs="1a"
  dat$hcr=hcrnum
  dat$scn=scnum
  dat$trp=trp
  dat$lrp=bl
  dat$thrp=bt
  dat$fmin=fmin
  
  dat1a = rbind(dat1a, dat)
}

#Extract results of one control point HCRs, HCR 9 and 10
btv=c(0.2,0.15)
blv=c(0.06,0.06)
trpv = c(0.2,0.25)
fminv= c(NA,NA)

hsnum=2
hcrnumv = c(109:110)
scnum = 1
hs = paste(hsnum, "/", sep = "")
scn = paste(scnum, "/", sep = "")

hcrnum=hcrnumv[1]
hcr = paste(hcrnum, "/", sep = "")
bt = btv[1]
bl = blv[1]
trp = trpv[1]
fmin = fminv[1]

dat2=read.table(paste(pdir,hs,hcr, scn, "/outmat",hsnum,hcrnum,scnum,".txt", sep =""))
dat2$hs=2
dat2$hcr=hcrnum
dat2$scn=scnum
dat2$trp=trp
dat2$lrp=bl
dat2$thrp=bt
dat2$fmin=fmin

for (j in 2:length(hcrnumv)){
  hcrnum=hcrnumv[j]
  hcr = paste(hcrnum, "/", sep = "")
  bt = btv[j]
  bl = blv[j]
  trp = trpv[j]
  fmin = fminv[j]
  
  dat=read.table(paste(pdir,hs,hcr, scn, "/outmat",hsnum,hcrnum,scnum,".txt", sep =""))
  dat$hs=2
  dat$hcr=hcrnum
  dat$scn=scnum
  dat$trp=trp
  dat$lrp=bl
  dat$thrp=bt
  dat$fmin=fmin
  
  dat2 = rbind(dat2, dat)
}

#combine output of all HCRs in one  data frame
dattot=rbind(dat1a, dat2)

#set directory where to store plots
setwd("C:/Users/desiree.tommasi/Documents/Bluefin/Plots")

#SSB wormplot
#compute second rebuilding target to draw line in plot
lrp1 = mean(dattot$outmat.B0om*0.2)

ssbwp=ggplot(dattot, aes(x=outmat.Year, y=outmat.SSB, color= as.factor(itr)))+ geom_line()+
  xlab("")+ylab("Spawning Stock Biomass (mt)")+ ggtitle("") + theme_bw()+
  geom_hline(yintercept=lrp1, linetype="dashed",color="black")+
  facet_wrap(~hcr)+guides(color="none")

dev.new(width=11, height=9)
png("ssb_wormp25.png", width = 15, height = 10, units = 'in', res = 300)
ssbwp
dev.off()

#Summarize MSE output across iterations
#SSB
dat3_ssbt = as.data.frame(dattot  %>% group_by(hcr, outmat.Year) %>% summarize(
  SSBm = mean (outmat.SSB, na.rm=TRUE),
  SSB5 = quantile(outmat.SSB, probs = 0.05, na.rm=TRUE),
  SSB95 = quantile(outmat.SSB, probs = 0.95, na.rm=TRUE),
  UBm = mean(outmat.B0om),
  LRPr = mean(lrp),
  Thrp = mean(thrp)
))

#depletion
dat3_dep = as.data.frame(dattot  %>% group_by(hcr, outmat.Year) %>% summarize(
  dep = mean (outmat.Depletion, na.rm=TRUE),
  d5 = quantile(outmat.Depletion, probs = 0.05, na.rm=TRUE),
  d95 = quantile(outmat.Depletion, probs = 0.95, na.rm=TRUE),
  LRPr = mean(lrp),
  Thrp = mean(thrp),
  trp= mean(trp)
))

#fishing intensity
dat3_ft = as.data.frame(dattot  %>% group_by(hcr, outmat.Year) %>% summarize(
  fm = mean ((1-outmat.SPR), na.rm=TRUE),
  f5 = quantile((1-outmat.SPR), probs = 0.05, na.rm=TRUE),
  f95 = quantile((1-outmat.SPR), probs = 0.95, na.rm=TRUE),
  trp = mean(trp)
))

#catch
dat3_ct = as.data.frame(dattot %>% group_by(hcr, outmat.Year) %>% summarize(
  cm = mean (outmat.Catch, na.rm=TRUE),
  c5 = quantile(outmat.Catch, probs = 0.05, na.rm=TRUE),
  c95 = quantile(outmat.Catch, probs = 0.95, na.rm=TRUE),
  LRPr = mean(lrp)
))

#recruitment
dat3_rt = as.data.frame(dattot %>% group_by(hcr, outmat.Year) %>% summarize(
  rm = mean (outmat.R, na.rm=TRUE),
  r5 = quantile(outmat.R, probs = 0.05, na.rm=TRUE),
  r95 = quantile(outmat.R, probs = 0.95, na.rm=TRUE),
))

#combine assessment and summarized MSE output into a data frame for plotting
ssbmat = data.frame(Year=c(rep(ssbdat$Year,12),dat3_ssbt$outmat.Year),
                    ssb=c(rep(ssbdat$SSB,12),dat3_ssbt$SSBm),
                    ssb5=c(rep(NA,828),dat3_ssbt$SSB5),
                    ssb95=c(rep(NA,828),dat3_ssbt$SSB95),
                    hcr=c(rep(101,69),rep(102,69),rep(103,69),rep(104,69),
                          rep(105,69),rep(106,69),rep(107,69),rep(108,69),
                          rep(109,69),rep(110,69),rep(111,69),rep(112,69),
                          dat3_ssbt$hcr))
c12 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F" # lt orange
)

setwd("C:/Users/desiree.tommasi/Documents/Bluefin/plots")

#SSB plot
ssbplot95=ggplot(ssbmat, aes(x=Year, y=ssb, color = as.factor(hcr))) + 
  geom_ribbon(aes(x=Year, ymin=ssb5, ymax=ssb95),fill="grey90",alpha=0.8)+
  geom_line(size=1)+xlab("")+ylab("Spawning Stock Biomass (mt)")+
  geom_vline(xintercept=2021, linetype="dashed",color="black")+
  theme_bw()+scale_colour_manual(values=c12,name = "HCR")+
  guides(color = "none")+facet_wrap(~hcr)

dev.new(width=10, height=8)
png("ssb95_omval25.png", width = 10, height = 8, units = 'in', res = 300)
ssbplot95
dev.off()

#relative biomass plot
dmat = data.frame(Year=c(rep(ssbdat$Year,12),dat3_dep$outmat.Year),
                  dep=c(rep((ssbdat$SSB/643582),12),dat3_dep$dep),
                  d5=c(rep(NA,828),dat3_dep$d5),
                  d95=c(rep(NA,828),dat3_dep$d95),
                  hcr=c(rep(101,69),rep(102,69),rep(103,69),rep(104,69),
                        rep(105,69),rep(106,69),rep(107,69),rep(108,69),
                        rep(109,69),rep(110,69),rep(111,69),rep(112,69),
                        dat3_dep$hcr),
                  lrp=c(rep(0.15,69),rep(0.15,69),rep(0.15,69),rep(0.15,69),
                        rep(0.2,69),rep(0.1,69),rep(0.1,69),rep(0.06,69),
                        rep(0.06,69),rep(0.06,69),rep(0.077,69),rep(0.077,69),
                        dat3_dep$LRPr),
                  thrp=c(rep(0.2,69),rep(0.25,69),rep(0.20,69),rep(0.25,69),
                         rep(0.25,69),rep(0.2,69),rep(0.2,69),rep(0.2,69),
                         rep(0.2,69),rep(0.15,69),rep(0.15,69),rep(0.2,69),
                         dat3_dep$Thrp),
                  trp=c(rep(0.3,69),rep(0.3,69),rep(0.4,69),rep(0.4,69),
                        rep(0.4,69),rep(0.3,69),rep(0.25,69),rep(0.3,69),
                        rep(0.2,69),rep(0.25,69),rep(0.3,69),rep(0.3,69),
                        dat3_dep$trp))

dplot95=ggplot(dmat, aes(x=Year, y=dep, color = as.factor(hcr))) + 
  geom_ribbon(aes(x=Year, ymin=d5, ymax=d95),fill="grey90",alpha=0.8)+
  geom_line(size=1)+xlab("")+ylab("Spawning Stock Biomass (fraction unfished)")+
  geom_vline(xintercept=2021, linetype="dashed",color="black")+
  geom_line(aes(x=Year, y=lrp),linetype="dashed",color="black")+
  geom_line(aes(x=Year, y=thrp),linetype="dashed",color="black")+
  geom_line(aes(x=Year, y=trp),linetype="dashed",color="red")+
  theme_bw()+scale_colour_manual(values=c12,name = "HCR")+
  guides(color = "none")+facet_wrap(~hcr)+ylim(0,1.25)

dev.new(width=10, height=8)
png("dep95_omval25.png", width = 10, height = 8, units = 'in', res = 300)
dplot95
dev.off()

#F plot
fmat = data.frame(Year=c(rep(fdat$Year,12),dat3_ft$outmat.Year),
                  fspr=c(rep(fdat$F,12),dat3_ft$fm),
                  f5=c(rep(NA,828),dat3_ft$f5),
                  f95=c(rep(NA,828),dat3_ft$f95),
                  hcr=c(rep(101,69),rep(102,69),rep(103,69),rep(104,69),
                        rep(105,69),rep(106,69),rep(107,69),rep(108,69),
                        rep(109,69),rep(110,69),rep(111,69),rep(112,69),
                        dat3_dep$hcr),
                  trp=c(rep(0.3,69),rep(0.3,69),rep(0.4,69),rep(0.4,69),
                        rep(0.4,69),rep(0.3,69),rep(0.25,69),rep(0.3,69),
                        rep(0.2,69),rep(0.25,69),rep(0.3,69),rep(0.3,69),
                        dat3_ft$trp))

fplot95=ggplot(fmat, aes(x=Year, y=fspr, color = as.factor(hcr))) + 
  geom_ribbon(aes(x=Year, ymin=f5, ymax=f95),fill="grey90",alpha=0.8)+
  geom_line(size=1)+xlab("")+ylab("Fishing Intensity (1-SPR)")+
  geom_vline(xintercept=2021, linetype="dashed",color="black")+
  geom_line(aes(x=Year, y=(1-trp)),linetype="dashed",color="black")+
  theme_bw()+scale_colour_manual(values=c12,name = "HCR")+
  guides(color = "none")+facet_wrap(~hcr)

dev.new(width=10, height=8)
png("f95_omval25.png", width = 10, height = 8, units = 'in', res = 300)
fplot95
dev.off()

#Catch plot
cmat = data.frame(Year=c(rep(cdat$Year,12),dat3_ct$outmat.Year),
                  catch=c(rep(cdat$Catch_mt,12),dat3_ct$cm),
                  c5=c(rep(NA,828),dat3_ct$c5),
                  c95=c(rep(NA,828),dat3_ct$c95),
                  hcr=c(rep(101,69),rep(102,69),rep(103,69),rep(104,69),
                        rep(105,69),rep(106,69),rep(107,69),rep(108,69),
                        rep(109,69),rep(110,69),rep(111,69),rep(112,69),
                        dat3_ct$hcr))

cplot95=ggplot(cmat, aes(x=Year, y=catch, color = as.factor(hcr))) + 
  geom_ribbon(aes(x=Year, ymin=c5, ymax=c95),fill="grey90",alpha=0.8)+
  geom_line(size=1)+xlab("")+ylab("Catch (mt)")+
  geom_vline(xintercept=2021, linetype="dashed",color="black")+
  theme_bw()+scale_colour_manual(values=c12,name = "HCR")+
  guides(color = "none")+facet_wrap(~hcr)

dev.new(width=10, height=8)
png("c95_omval25.png", width = 10, height = 8, units = 'in', res = 300)
cplot95
dev.off()

#recruitment plot
rmat = data.frame(Year=c(rep(rdat$Year,12),dat3_rt$outmat.Year),
                  rec=c(rep((rdat$Recruits),12),dat3_rt$rm),
                  r5=c(rep(NA,828),dat3_rt$r5),
                  r95=c(rep(NA,828),dat3_rt$r95),
                  hcr=c(rep(101,69),rep(102,69),rep(103,69),rep(104,69),
                        rep(105,69),rep(106,69),rep(107,69),rep(108,69),
                        rep(109,69),rep(110,69),rep(111,69),rep(112,69),
                        dat3_rt$hcr))

rplot95=ggplot(rmat, aes(x=Year, y=rec, color = as.factor(hcr))) +
  geom_ribbon(aes(x=Year, ymin=r5, ymax=r95),fill = "grey90",alpha=0.8)+
  geom_line()+xlab("")+ylab("Recruits (#)")+
  geom_vline(xintercept=2021, linetype="dashed",color="black")+
  theme_bw()+scale_colour_manual(values=c12,name = "HCR")+
  guides(fill = "none")+facet_wrap(~hcr)

dev.new(width=10, height=8)
png("rec95_omval25.png", width = 10, height = 8, units = 'in', res = 300)
rplot95
dev.off()